apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-storage
  labels:
    app.kubernetes.io/name: model-storage
    app.kubernetes.io/managed-by: manual
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: "local-path"
