inferenceExtension:
  replicas: 1
  image:
    # both downstream infernece-scheduler and upstream epp image can support inference-scheduling example
    ###################
    name: inference-scheduler
    hub: harbor.qifand.com/llm-infer
    tag: latest
    # name: llm-d-inference-scheduler
    # hub: ghcr.io/llm-d
    # tag: v0.3.2
    ###################
    # name: epp
    # hub: registry.k8s.io/gateway-api-inference-extension
    # tag: v1.0.1
    ###################
    pullPolicy: Always
  env:
    - name: INFERENCE_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgresql-credential
          key: admin-password
    - name: INFERENCE_DB_URL
      value: "postgresql-cluster-rw.postgresql.svc.cluster.local"
    - name: INFERENCE_DB_USERNAME
      value: "admin"
    - name: INFERENCE_DB_NAME
      value: "logsdb"
    - name: INFERENCE_DB_SCHEMA
      value: "metrics"
    - name: INFERENCE_DB_TABLE
      value: "scheduler"
    - name: INFERENCE_DB_PORT
      value: "5432"
  extProcPort: 9002
  pluginsConfigFile: "default-plugins.yaml"
  monitoring:
    interval: "10s"
    # Service account token secret for authentication
    secret:
      name: inference-scheduling-gateway-sa-metrics-reader-secret
    # Prometheus ServiceMonitor will be created when enabled for EPP metrics collection
    prometheus:
      enabled: true
inferencePool:
  apiVersion: inference.networking.x-k8s.io/v1alpha2 # use old API version for inference
  targetPortNumber: 8000
  modelServerType: vllm
  modelServers:
    matchLabels:
      llm-d.ai/inferenceServing: "true"
